# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import microservice_comms_pb2 as microservice__comms__pb2


class HandlerStub(object):
    """handles the microservice request and gives and acknowledgement as a response.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HandleRequest = channel.unary_unary(
                '/microserviceComms.Handler/HandleRequest',
                request_serializer=microservice__comms__pb2.microserviceCommsRequest.SerializeToString,
                response_deserializer=microservice__comms__pb2.microserviceCommsACK.FromString,
                )


class HandlerServicer(object):
    """handles the microservice request and gives and acknowledgement as a response.
    """

    def HandleRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HandlerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'HandleRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.HandleRequest,
                    request_deserializer=microservice__comms__pb2.microserviceCommsRequest.FromString,
                    response_serializer=microservice__comms__pb2.microserviceCommsACK.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'microserviceComms.Handler', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Handler(object):
    """handles the microservice request and gives and acknowledgement as a response.
    """

    @staticmethod
    def HandleRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/microserviceComms.Handler/HandleRequest',
            microservice__comms__pb2.microserviceCommsRequest.SerializeToString,
            microservice__comms__pb2.microserviceCommsACK.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
