# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: microservice_comms.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18microservice_comms.proto\x12\x11microserviceComms\",\n\x18microserviceCommsRequest\x12\x10\n\x08\x63ol_name\x18\x01 \x01(\t\"\"\n\x14microserviceCommsACK\x12\n\n\x02\x64\x66\x18\x01 \x01(\t2r\n\x07Handler\x12g\n\rHandleRequest\x12+.microserviceComms.microserviceCommsRequest\x1a\'.microserviceComms.microserviceCommsACK\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'microservice_comms_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MICROSERVICECOMMSREQUEST._serialized_start=47
  _MICROSERVICECOMMSREQUEST._serialized_end=91
  _MICROSERVICECOMMSACK._serialized_start=93
  _MICROSERVICECOMMSACK._serialized_end=127
  _HANDLER._serialized_start=129
  _HANDLER._serialized_end=243
# @@protoc_insertion_point(module_scope)
